CREATE TABLE LOGIN_DETAILS(
LOGIN_ID SERIAL PRIMARY KEY,
USERNAME VARCHAR(20) NOT NULL UNIQUE,
PASSWORD VARCHAR(100) NOT NULL ,
NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
LAST_LOGIN_DATE TIMESTAMP NOT NULL DEFAULT now(),
TOKEN VARCHAR(250),
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

CREATE TABLE TELECOM_PLAN(
PRODUCT_ID SERIAL PRIMARY KEY,

)

CREATE TABLE PRODUCT (
PRODUCT_ID SERIAL PRIMARY KEY,
PRODUCT_NAME VARCHAR(30) NOT NULL UNIQUE,
DESCRIPTION VARCHAR(100) NOT NULL ,
PRICE NUMERIC(10,3) NOT NULL,
QUANTITY INTEGER NOT NULL DEFAULT 0,
IMAGE_PATH VARCHAR(200),
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

CREATE TABLE PRODUCT_SALES (
SALES_ID SERIAL PRIMARY KEY,
PRODUCT_ID INTEGER REFERENCES PRODUCT(PRODUCT_ID),
QUANTITY INTEGER NOT NULL,
TOTAL_AMOUNT NUMERIC(10,3) NOT NULL,
CUSTOMER_ID INTEGER REFERENCES LOGIN_DETAILS(LOGIN_ID),
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);


CREATE TABLE CONFIG_MASTER(
CONFIG_MASTER_ID SERIAL PRIMARY KEY,
CONFIG_NAME VARCHAR(20) NOT NULL UNIQUE,
CONFIG_DESC VARCHAR(50) NOT NULL UNIQUE,
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

CREATE TABLE CONFIG_DETAILS(
CONFIG_DETAILS_ID SERIAL PRIMARY KEY,
CONFIG_MASTER_ID INTEGER REFERENCES  CONFIG_MASTER(CONFIG_MASTER_ID),
KEY VARCHAR(20) NOT NULL ,
VALUE VARCHAR(20) NOT NULL ,
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

