CREATE TABLE LOGIN_DETAILS(
LOGIN_ID SERIAL PRIMARY KEY,
USERNAME VARCHAR(20) NOT NULL UNIQUE,
PASSWORD VARCHAR(30) NOT NULL ,
NAME VARCHAR(30) NOT NULL,
LAST_LOGIN_DATE TIMESTAMP NOT NULL DEFAULT now(),
TOKEN VARCHAR(250),
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);


CREATE TABLE CONFIG_MASTER(
CONFIG_MASTER_ID SERIAL PRIMARY KEY,
CONFIG_NAME VARCHAR(20) NOT NULL UNIQUE,
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

CREATE TABLE CONFIG_DETAILS(
CONFIG_DETAILS_ID SERIAL PRIMARY KEY,
CONFIG_MASTER_ID INTEGER REFERENCES  CONFIG_MASTER(CONFIG_MASTER_ID),
KEY VARCHAR(20) NOT NULL ,
VALUE VARCHAR(20) NOT NULL ,
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

CREATE TABLE ASAP_REQUEST_MASTER(
ASAP_REQ_ID SERIAL PRIMARY KEY,
ASAP_REQ_TYPE VARCHAR(30) NOT NULL UNIQUE,
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

CREATE TABLE ASAP_REQUEST_XML(
ASAP_REQ_XML_ID SERIAL PRIMARY KEY,
ASAP_REQ_ID INTEGER  REFERENCES ASAP_REQUEST_MASTER(ASAP_REQ_ID),
REQ_XML_PART VARCHAR(4000) NOT NULL,
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

CREATE TABLE ASAP_REQUEST_XML_PARAM(
ASAP_REQ_XML_PARAM_ID SERIAL PRIMARY KEY,
ASAP_REQ_ID INTEGER  REFERENCES ASAP_REQUEST_MASTER(ASAP_REQ_ID),
PARAM_NAME VARCHAR(20) NOT NULL,
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

CREATE TABLE ASAP_REQUEST_MASTER(
ASAP_REQ_MAS_ID SERIAL PRIMARY KEY,
ASAP_REQ_ID INTEGER  REFERENCES ASAP_REQUEST_MASTER(ASAP_REQ_ID),
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);

CREATE TABLE ASAP_REQUEST_DETAILS(
REQ_DET_ID SERIAL PRIMARY KEY,
ASAP_REQ_MAS_ID INTEGER  REFERENCES ASAP_REQUEST_MASTER(ASAP_REQ_MAS_ID),
REQ_XML_PART VARCHAR(4000) NOT NULL,
CREATED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
MODIFIED_USER_ID VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT now(),
DELETION_STATUS CHAR(1) DEFAULT 'N'
);